### ISSUE TITLE
Enable non-EN speakers to easily access research

### ISSUE THREAD

**Issue by silviaprt** [higgood/seechat-folks#11]
**Is your feature request related to a problem? Please describe.**
Not every person might be able to fully benefit from the tool capabilities if these are provided only in English. Access to research would have a lot more impact if it allowed any person to interact in their most familiar language.

**Describe the solution you'd like**
1) Support requests in other languages and respond in same language
2) Even for EN requests, support the possibility to select the language of the response (whether generated or simply translated)

**Comment by wammar** [comment]
We just started an R&D project with @MariamHossam00  to address this feature request. Thank you @silviaprt !

**Comment by tashacabrera** [comment]
Baster will be looking for collaborators who want to add data to this project.

**Comment by wammar** [comment]
This task is now resolved since the project is well underway.
