### ISSUE TITLE
Quick feedback and research question ranking

### ISSUE THREAD

**Issue by silviaprt** [higgood/seechat-folks#12]
**Is your feature request related to a problem? Please describe.**
Lots of topics will be similar, so why not enable users to promote certain ideas and responses by a simple voting system such as thumb up/down

**Describe the solution you'd like**
Allow users to label each response with a thumb up/down and use the information to:
- improve model
- take top research questions into account when asked about the same or a similar topic and possibly present them to the user
- have a top rated research questions page/panel in the tool where users can explore peer-vetted research ideas.

**Comment by tashacabrera** [comment]
We have added the thumbs up/down feature. Attached is a screenshot below. @silviaprt what do you think of this design?
![image](https://github.com/higgood/seechat-folks/assets/146769751/c8eb211e-cae8-4ceb-96f7-08df29bc27df)

**Comment by silviaprt** [comment]
That's perfect. Thanks!

**Comment by wammar** [comment]
@muhammadnasr Which icon did we decide to use? Thumbs up/down OR Arrow up/down?

**Comment by muhammadnasr** [comment]
I like the thumbs up/down.
I think you are OK with using them in both view and creator mode.

**Comment by wammar** [comment]
Iryna updated the design to include one option.

**Comment by wammar** [comment]
Resolved because design is done, and there's a separate issue for engineering (thumbs up/down).
