### ISSUE TITLE
The ideas generated are a bit too abstract

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#14]
**Context**
I'm a power user.

**Describe the bug**
It's not a bug exactly but it'd be nice if the ideas generated were more actionable.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
A clear and concise description of the unexpected behavior that actually happened vs. what you were hoping would happen. (So sorry for your pain; We pinch ourselves everytime someone reports a bug in order to feel your pain.)

**Screenshots**

**Desktop (if applicable):**

**Smartphone (if applicable):**

**Additional context**

Thank you for improving the Idea Factory!!

**Comment by tashacabrera** [comment]
This is resolved. @Mox301 worked on improving this. Thank you
