### ISSUE TITLE
Idea details are not generated .. at all.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#18]
**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[x] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Reality: After I clicked "THINK" and the related work section was generated, the idea details were NOT generated. I patiently waited 3 minutes, then filed this bug.
Expectation: I expected the idea details to be generated.

**Screenshots**
![image](https://github.com/higgood/seechat-folks/assets/1858803/c3829ae5-1fed-4fe2-b523-79c3ed2fb7fd)

**Desktop (if applicable):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: Version 125.0.2535.92 (Official build) (64-bit)

**Comment by muhammadnasr** [comment]
| openai.error.AuthenticationError: Incorrect API key provided: sk-proj-********************************************7fuP. You can find your API key at https://platform.openai.com/account/api-keys.
    | 
    | During handling of the above exception, another exception occurred:
    
    @Mox301 on it, seems key is expired

**Comment by muhammadnasr** [comment]
OpenAI key updated.
Our users can now enjoy generating ideas.
Thanks @Mox301
