### ISSUE TITLE
Logged in users should not be able to play until they accept all terms.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#20]
**Context**
A UX interview with an early adopter. After the user clicked on the "magic link" in the authentication email sent to them for the first time, they were redirected to the settings page, input their alias.

**Describe the bug**
The user neglected to accept the terms yet they were able to go to the main screen, provide input, and click "THINK".  (Then, the user was asked to go back to the settings page and accept the terms.)

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[x] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Expectation: Until the logged-in user accept the terms, the only screen they are allowed to see is the settings page.
Reality: Logged in users who didn't accept the terms are able to go to the main page and type in problem/scientific areas.

**Screenshots**
Video session: https://drive.google.com/file/d/1-yylqZZjGLbfnwWzOycNzjDaTMWyg0t2/view?usp=sharing

**Smartphone:**
- Device: Samsung.
 - OS: Android.
 - Browser: Chrome

**Comment by wammar** [comment]
@muhammadnasr believes this is now fixed on staging. 

@wammar to verify.

**Comment by muhammadnasr** [comment]
@wammar please verify at production
