### ISSUE TITLE
Add paper links to the "Used references" section.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#23]
**Is your feature request related to a problem? Please describe.**
Sometimes, the idea summary and related work sections refer to a paper without providing a link. I wanted to actually read the paper so I scrolled down and found it in the list of references, but had to go through the hassle of copy-pasting the text, finding the paper in the search results. 

**Describe the solution you'd like**
Please add a link to the paper in the paper card (which looks great by the way).

**Describe alternatives you've considered**
If you want to get more fancy, consider providing multiple links like semantic scholar does.

**Comment by theophilaabigail** [comment]
Suggested Solution : 
- Add a copy link icon to copy the paper url.

**Comment by wammar** [comment]
Duplicate of https://github.com/higgood/seechat/issues/461

**Comment by Iryna-Boboshko** [comment]
@wammar added 'Copy link' icon


![Image](https://github.com/user-attachments/assets/48f1d861-fe0d-4308-ab73-52782212cfff)

**Comment by wammar** [comment]
Next step is for Bridger to create a task for engineering to implement this.

**Comment by wammar** [comment]
Please use the figma file v8 for the latest version of the design.

**Comment by muhammadnasr** [comment]
@Mox301 please add the link to the current design (don't use new floating design)
 implement the link button to open in a new page
