### ISSUE TITLE
demo.seechat.ai is rejecting people's payments

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#28]
**Describe the bug**
Paying functionality is broken on demo.seechat.ai

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[x] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Expectation: A user should be able to pay to increase their credits.
Reality: A user is asked to use a test code.

**Screenshots**
![image](https://github.com/higgood/seechat-folks/assets/1858803/8714f1d4-6b24-4ea0-bcac-e4f88ebd9fdb)

**Desktop (if applicable):**
 - OS: Windows 11
 - Browser Edge

**Comment by muhammadnasr** [comment]
Demo environment is not using production settings for payment.
Feel free to use test card repeat (42)

**Comment by wammar** [comment]
Duplicate #26
