### ISSUE TITLE
Can't delete bad references.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#31]
**Context**
100th time.

**Describe the bug**
I'm unable to remove bad references from the list of used references, which prevents me from sharing a link to the idea.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[x] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Expectation: I expect to be able to delete papers.
Reality: I can't.

**Screenshots**
![image](https://github.com/higgood/seechat-folks/assets/1858803/8d27c797-1be2-4ecf-8d07-540bdddb1504)

**Desktop (if applicable):**
 - OS: Windows
 - Browser Edge

Thank you for improving the Idea Factory!!

**Comment by tashacabrera** [comment]
I am unable to remove the bad references.

**Comment by muhammadnasr** [comment]
@wammar we need UI for "delete" button and alert "are you sure you want to delete this paper"?
Also we assume that the user will delete the paper paragraph from the literature review manually and update paper indexes.

**Comment by wammar** [comment]
@muhammadnasr any progress on this?

@Iryna-Boboshko please add a delete icon to the paper cards.

**Comment by muhammadnasr** [comment]
ُThis feature is implement locally but we need the design for icon and the
confirmation popup
