### ISSUE TITLE
Literature review DISAPPEARS while I'm reading it.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#34]
**Context**
During a user study, a scientist who expressed great interest in the product was reading the literature review when it suddenly disappeared to show the idea details instead. I've seen many users implicitly show signs of surprise and dissatisfaction when this happens in user studies.

**Describe the bug**
The literature review disappears in favor of the idea summary, which confuses the user and disrupts their use of the product.
 
**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[x] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Reality: The literature review text box disappeared.
Expectation: The user expected that the literature review does not move, but some other visual show on the screen to notify the user that they can read the idea summary if they scroll down.
 
**Screenshots**
N/A

**Desktop (if applicable):**
 - OS: Windows 11
 - Browser: Edge

Thank you for improving the Idea Factory!!

**Comment by wammar** [comment]
More people are complaining about this.

**Comment by Mox301** [comment]
@wammar this addressed here is this PR https://github.com/higgood/seechat/pull/357
