### ISSUE TITLE
empty notification box when the query is empty

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#35]
**Describe the bug**
When I click on Think without typing anything, an empty notification box appears for a few seconds.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[x] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Expectation: Either pick a meaningful problem for the user to reduce user friction, or provide a helpful notification.
Reality: an empty notification message: 
![image](https://github.com/higgood/seechat-folks/assets/1858803/4cdc1dea-d7de-403a-9cf2-94c95fbf25e4)

**Desktop (if applicable):**
 - OS: Windows 11
 - Browser: Edge

Thank you for improving the Idea Factory!!

**Comment by tashacabrera** [comment]
I am experiencing this on my end too.

**Comment by muhammadnasr** [comment]
Fixed
