### ISSUE TITLE
Idea title is way too long

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#43]
**Describe the bug**
The title can be very long: "Identifying the ideal customer profile for a new product requires an analytical and holistic approach to understand the potential market's behaviors, needs, desires, and characteristics. Implementing an Adaptive Real-Time Customer Profiling Framework (ARC-PF) leverages Big Data, AI-powered analytics, and comprehensive market research to provide a nuanced view of potential customers. This framework dynamically adjusts based on new data, offering real-time insights and enabling precise marketing strategies, continuous product innovation, and strategic business decisions, ensuring sustained relevance and competitiveness in rapidly changing markets." [example](https://demo.seechat.ai/idea/bcc3471a-55b3-477d-8856-57960dbe7bff/Identifying-the-ideal-customer-profile-for-a-new-product-requires)

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[x] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Expectation: 10 words.
Reality: 88 words.

**Screenshots**
![image](https://github.com/higgood/seechat-folks/assets/1858803/1305b28c-32c1-4980-9c19-da70cccfd603)

**Desktop (if applicable):**
 - OS: Windows 11
 - Browser: Edge

**Additional context**
More discussion on [slack](https://thinksparkgroup.slack.com/archives/D05NVRZH3S8/p1719900424719159) (only accessible to bridger and moamen).

Thank you for improving the Idea Factory!!

**Comment by Mox301** [comment]
solved in this PR https://github.com/higgood/seechat/pull/397
