### ISSUE TITLE
Title generation is recently broken.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#50]
**Context**
Frequent user.

**Describe the bug**
The title produced in the last few ideas I tried is too long, and is identical to the first paragraph of the idea summary. 

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[x] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Reality: The text generated in the Title field is almost identical to the first few sentences in the Idea Summary Field.
Expectation: Title should not exceed 10 words.

**Screenshots**
![image](https://github.com/user-attachments/assets/356beac1-380b-4cf6-9928-0cf4ea8de1cb)

![image](https://github.com/user-attachments/assets/5d1a1a22-23d6-4237-9c5b-3c4a62633081)

**Desktop (if applicable):**
 - OS: Windows 11 
 - Browser: Edge

**Smartphone (if applicable):**
 - Device: iPhone SE
 - OS: iOS
 
**Additional context**
The screenshots above are taken from these URLs:
- https://seechat.ai/idea/bb421cbb-a9dd-49bc-a825-d58f78844903/To-convince-university-professors-to-try-out-a-new-product%2C
- https://seechat.ai/idea/88c5d761-e961-4119-b2e0-685496d6b723/88c5d761-e961-4119-b2e0-685496d6b723
- 
Thank you for improving the Idea Factory!!

**Comment by Mox301** [comment]
solved in this PR https://github.com/higgood/seechat/pull/397
