### ISSUE TITLE
Accessing Ideas without being a user

### ISSUE THREAD

**Issue by OmarAminAI** [higgood/seechat-folks#51]
**Context**
i was researching the APIs of seechat.ai trying to find them out when i came across this situation where i was able to see the ideas without having any account what-so-ever

**Describe the bug**

1. being able to bypass the welcoming page ideas just by adding "/anything" 

2. and by accessing one of the idea's i can type a problem and when using "Think" button nothing happens shouldn't it redirect 

**[Required] Where did you encounter the bug**
while researching for the APIs

**[Required] Reality vs. Expectation**
i was expecting that it would redirect me to the welcoming page again.

**Screenshots**
![image](https://github.com/user-attachments/assets/4943cb4c-272d-4d3d-8063-c0e4f7531dd6)
![image](https://github.com/user-attachments/assets/8ed56166-d902-4017-80ca-7f1247a2b060)

**Desktop (if applicable):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [N/A]

Thank you for improving the Idea Factory!!

**Comment by wammar** [comment]
1 is a feature not a bug.

**Comment by wammar** [comment]
2 is a bug, reported elsewhere.

**Comment by wammar** [comment]
Duplicate #56

**Comment by wammar** [comment]
Thank you for reporting @OmarAminAI
