### ISSUE TITLE
Credit updates after usage

### ISSUE THREAD

**Issue by OmarAminAI** [higgood/seechat-folks#52]
**Is your feature request related to a problem? Please describe.**
after generating an idea the credits do not update, for it to update i would need to manually refresh the page

**Describe the solution you'd like**
credits updates after each usage

**Describe alternatives you've considered**
code it to dynamically update after each click on "Think" button

**Additional context**
[URL to idea](https://seechat.ai/idea/eadc10b0-e5a4-4a5d-863e-fe3c1cd5343c/eadc10b0-e5a4-4a5d-863e-fe3c1cd5343c)

**Comment by wammar** [comment]
This is a high priority item because it diminishes user trust in SeeChat x Ideas.
