### ISSUE TITLE
Nothing seems to happen when logged-in user clicks on 'Think' with an obscure scientific area.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#57]
**Context**
During a [user study](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NzZzOG9oaWZma3RrcmdnbmxzcTB1aDVxc2Ygd2FtbWFyQGhvbGlzdGljLWludGVsbGlnZW5jZS5uZXQ&tmsrc=wammar%40holistic-intelligence.net), the user provided a detailed, long input problem statement followed by "RAG" as a scientific area.

**Describe the bug**
No output or error message were displayed on the user's screen when they clicked "Think".

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[ ] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[x] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Expectation: an idea 
Reality: nothing.

**Screenshots**
N/A

**Smartphone (if applicable):**
 - Device: Samsung
 - Browser: Edge

**Additional context**
User submitted feedback sometime during the session to help us diagnose the issue.

Thank you for improving the Idea Factory!!

**Comment by wammar** [comment]
Replicated: 

![Image](https://github.com/user-attachments/assets/6c3c9eb2-2670-42b4-9d9b-c21030c0e97a)

**Comment by wammar** [comment]
@Mox301 will investigate.

**Comment by wammar** [comment]
Notification error: No results found. Please rewrite your problem statement and scientific areas to get more results. Use the 'Give feedback' button if you think we should return results for this input.

**Comment by Mox301** [comment]
Solved in this PR https://github.com/higgood/seechat/pull/412

**Comment by muhammadnasr** [comment]
We will use this message as suggested by @wammar and @ma7dy 
"No results found. Please try a different input."

**Comment by muhammadnasr** [comment]
Fixed on production
