### ISSUE TITLE
More intuitive ways of exploring the ideas/problems

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#64]
**Is your feature request related to a problem? Please describe.**
I'm trying to find interesting public ideas other people created on SeeChat x Ideas. I currently do this by clicking on the burger menu, unchecking the "my ideas only" box, then reading through the topics but it's unclear to me as a user how these topics were selected, and why should I care about them.

**Describe the solution + alternatives you'd like**
- Compute similarity score between the problems a user provided in the past and existing ideas.
- Provide a way to search problems.
- Provide a way to search solutions.
- Provide a way to filter by date.
- Provide a way to order by relevance.
- Provide a way to filter by geographic region.
- Make it visually obvious that the user can expand each topic in the side panel by clicking on it.
- Use a divider between ideas when a topic is expanded.
- Limit each idea to one line in the expanded view (see screenshot below).
![image](https://github.com/user-attachments/assets/4f57838b-77ea-4626-9a67-26f0e984c578)

**Comment by wammar** [comment]
Next step is to collect user input in the next UX survey.

**Comment by tashacabrera** [comment]
Assigned to Gabr.

**Comment by wammar** [comment]
@ahmedoy prepared the survey and it's being reviewed by baster and I before we send it out.

**Comment by wammar** [comment]
Duplicate https://github.com/higgood/ops/issues/807
First step towards this is https://github.com/higgood/ops/issues/807 . When it's done, we'll follow through as needed.
