### ISSUE TITLE
Having to re login every time a user wants to enter seechat x ideas.

### ISSUE THREAD

**Issue by nova-sudo** [higgood/seechat-folks#68]
**Is your feature request related to a problem? Please describe.**
having to not just login, but waiting for an email is not time efficient and might be a bit of a complication for some users

**Describe the solution you'd like**
create timed sessions for users, example: 24 - 48 hours and then they'll have to login again.

**Comment by wammar** [comment]
Thank you for suggesting this. We modified our authentication to have longer session times.

**Comment by Ahmed-Habashy** [comment]
Problem solved
